### ISSUE TITLE
BUG: can't work for static build program

### ISSUE THREAD

**Issue by Hackerl** [MikhailProg/elf#6]
![image](https://user-images.githubusercontent.com/15811751/125764937-b747d065-ba60-4bac-8eb2-f2c694256ab0.png)
it work if don't call ["x_fini"](https://github.com/MikhailProg/elf/blob/master/src/loader.c#L22).

**Comment by tufeigunchu** [comment]
It works in fact if you custom its start address

**Comment by MikhailProg** [comment]
remove calling fini callback from ld.so it causes a crash, test.sh is added, tested with gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
